name: Test Build
on:
  push:
  workflow_dispatch:
  watch:
    types: [started]

env:
  MANIFEST: "https://github.com/PitchBlackRecoveryProject/manifest_pb -b android-10.0"
  DT_LINK: "https://github.com/PitchBlackRecoveryProject/android_device_xiaomi_phoenix-pbrp"
  VENDOR: "xiaomi"
  CODENAME: "phoenix"
  TARGET: "recoveryimage"
  FLAVOR: "eng"
  TZ: "Asia/Kolkata"
  BUILD_RELEASE_TYPE: "TEST"
  BOT_API: ${{ secrets.BOT_API }}
  GCF_AUTH_KEY: ${{ secrets.GCF_AUTH_KEY }}
  GH_BOT_TOKEN: ${{ secrets.GH_BOT_TOKEN }}
  GitHubMail: ${{ secrets.GitHubMail }}
  GitHubName: ${{ secrets.GitHubName }}
  SFPassword: ${{ secrets.SFPassword }}
  SFUserName: ${{ secrets.SFUserName }}

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
       - name: Mock Build
         run: |
          # Mock Official Build
          mkdir -p work/out/target/product/phoenix
          touch work/out/target/product/phoenix/PBRP-phoenix-3.0.0-20210214-2119-UNOFFICIAL.zip
          touch work/out/target/product/phoenix/recovery.img

       - name: Setup Deps
         run: |
             sudo apt-get install sshpass -y
             sudo snap install --classic --channel=1.15/stable go 
             go get -u github.com/tcnksm/ghr

       - name: PB deploy
         run: |
              cd work
              git clone https://github.com/PitchBlackRecoveryProject/vendor_utils vendor/utils
              git clone https://github.com/PitchBlackRecoveryProject/android_bootable_recovery bootable/recovery
              wget https://raw.githubusercontent.com/PitchBlackRecoveryProject/vendor_utils/pb/pb_deploy.sh
              export PATH="/home/runner/go/bin:$PATH"
              bash pb_deploy.sh ${BUILD_RELEASE_TYPE} ${VENDOR} ${CODENAME}
